// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATduVfoir9MEoG4NjFrYO-Wnm0qYCumYs',
    appId: '1:1000406793672:android:82b9f9512eb1e1b96354fd',
    messagingSenderId: '1000406793672',
    projectId: 'compu-paralela',
    storageBucket: 'compu-paralela.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2baQ-bABzDYZNhQH-Z4xar4IuPSu5RI',
    appId: '1:1000406793672:ios:4b5405b20260a4a96354fd',
    messagingSenderId: '1000406793672',
    projectId: 'compu-paralela',
    storageBucket: 'compu-paralela.appspot.com',
    androidClientId: '1000406793672-nb8jv2d3p14ghuk3g1v35trolen6bfmj.apps.googleusercontent.com',
    iosClientId: '1000406793672-5u84k1m2r7megvjdnqmk38sjn0a41s9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
